---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vnext-nginx-persistentvolume
  resourceVersion: '63509'
  finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Mi
  hostPath:
    path: "/aStorage/nginx-vnext"
    type: ''
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
