---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-persistentvolume
  resourceVersion: '63509'
  finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Mi
  hostPath:
    path: "/aStorage/nginx"
    type: ''
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-persistentvolumeclaim
  namespace: default
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
  - ReadWriteMany


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
      version: "1"
  template:
    metadata:
      labels:
        app: nginx-pod
        version: "1"
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginxvol
      volumes:
        - name: nginxvol
          persistentVolumeClaim:
            claimName: nginx-persistentvolumeclaim  

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-pod
    version: "1"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: nginxhost
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 80    
