---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vnext-nginx-persistentvolumeclaim
  namespace: default
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
  - ReadWriteMany